### ISSUE TITLE
https://dtp-stat.ru/api/auth/me 401

### ISSUE THREAD

**Issue by ustnv** [dtpstat/dtp-stat#85]
При запуске карты постоянно вылазит ошибка в консоли

**Comment by alexander-mart** [comment]
@ustnv полагаю, вопрос можно закрыть, ошибка не является проблемой и лишь указывает на статус (необязательной) аутентификации пользователя для использования раздела «Комментарии»

Например: https://dtp-stat.ru/dtp/221354126/#comments
> Комментариев — 0
> Для оставления комментария [авторизуйтесь](https://dtp-stat.ru/api/auth/login?returnTo=%2Fiframes%2Fcomments%3Faccident-id%3D221354126%26iframe-auth%3Dtrue).
