### ISSUE TITLE
Настроить генерацию sitemap.xml

### ISSUE THREAD

**Issue by ustnv** [dtpstat/dtp-stat#88]
В архивном проекте, кстати, было
https://github.com/dtpstat/dtp-stat-archive/blob/master/dtpmapapp/sitemaps.py 

и еще robot.txt

**Comment by PiRomant** [comment]
Лучше добавить в https://github.com/dtpstat/dtp-stat/issues/20

**Comment by ustnv** [comment]
duplicate of #20
